# Generated by Django 2.2.8 on 2020-04-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('post_type', models.CharField(max_length=100, verbose_name='贴子类型')),
                ('post_img', models.ImageField(upload_to='post_img/', verbose_name='贴子配图')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发表时间')),
                ('browse_nums', models.IntegerField(default=0, verbose_name='贴子浏览')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_posts', to='user.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '贴子',
                'verbose_name_plural': '贴子',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('zan_nums', models.IntegerField(default=0, verbose_name='获赞')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_comments', to='post.Post', verbose_name='对应帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_comments', to='user.User', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '贴子评论',
                'verbose_name_plural': '贴子评论',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_replies', to='post.PostComment', verbose_name='对应评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_replies', to='user.User', verbose_name='回复者')),
            ],
            options={
                'verbose_name': '评论回复',
                'verbose_name_plural': '评论回复',
            },
        ),
    ]
